<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Dracocephalum.Nightingale.Examples.CatchUpSubscription/Dracocephalum.Nightingale.Examples.CatchUpSubscription.csproj" />
  </ItemGroup>

</Project>
